# Setting name and title fixes duplicated header issue
name: serranomorante
title: null
plugins:
  - jekyll-katex
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter
  - jekyll-pandoc
markdown: Pandoc
theme: jekyll-theme-primer
# The GitHub repository that we are hosting our foam workspace from
repository: serranomorante/foam
# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty
pandoc:
  extensions:
    - katex
    - bibliography: public/myrefs.bib
